<template>
  <CaseLayout
    :path="$route.path"
    introText="Collaboration with real estate developer on Cyprus for tracking the daily distribution, consumption and offsetting any excess carbon footprint."
    introImg="fronius-solar-web/1.png"
    link="https://github.com/Multi-Agent-io/solarweb-hass-integration"
    linkText="solarweb-hass-integration"
  >

    <section class="case-page__content">
      <CaseText
        title="In a nutshell"
        text="Nowadays, it becomes more and more clear that energy consumption is a major contributor to carbon footprints, making it increasingly important to find ways to reduce our environmental impact. Offices and commercial buildings play a significant role in this energy consumption. The engineers at Robonomics have installed a system in the office of BBF, a Cyprus-based real estate developer, to track and collect electricity measurements. This system also provides a practical way to offset the carbon footprint."
        img="fronius-solar-web/2.png"
        imgAlt="fronius-solar-web"
      />
      <CaseText
        title="1. Monitoring surplus energy generation"
        text="At the BBF company's office building, several solar panels have been installed and integrated into the Solarweb system, enabling easy collection of analytics. The system provides data on the building's overall electricity consumption and the electricity generated by the solar panels. However, a crucial missing feature is the capability to offset the carbon footprint resulting from the electricity consumed beyond what is generated by the solar panels."
        img="fronius-solar-web/3.png"
        imgAlt="fronius-solar-web"
      />
      <CaseText
        title="2. Converting excess energy power to CO2 offset"
        multiply
        img="fronius-solar-web/4.png"
        imgAlt="fronius-solar-web"
      >
        <p>Having data on the total electricity consumption and the solar panels' electricity production allows for a straightforward calculation of the carbon footprint. It is assumed that electricity from solar panels has a carbon footprint of 0, which means compensation is necessary only for the excess electricity consumed beyond what the solar panels generated.</p><p>Notably, CO2 emissions differ across countries. In Cyprus, the average pollution stands at 587 g/kWh, according to Hannah Ritchie, Max Roser, and Pablo Rosado (2022) - "Energy".</p><p>To offset the carbon footprint, carbon credits are utilized, with each credit representing 1 ton of CO2. These credits play a vital role in compensating for the environmental impact caused by electricity consumption beyond the solar panels' contribution.</p>
      </CaseText>
      <CaseText
        title="3. Managing blockchain-verified carbon footprint offset"
        multiply
        img="fronius-solar-web/5.png"
        imgAlt="fronius-solar-web"
      >
        <p>Thus, armed with data on energy consumption, solar panel production, and the Cyprus coefficient, it becomes effortless to determine the number of tokens required for carbon footprint offset.</p><p>To achieve this, we incorporated a Raspberry Pi, configured Home Assistant to collect analytical data, and developed an integration for compensating the footprint. The Home Assistant energy dashboard showcases the following details:</p>
      </CaseText>
      <p>Furthermore, our integration enhances the system by offering a convenient control panel to view statistics and trigger compensation:</p>
      <g-image src="@/assets/images/cases/fronius-solar-web/6.png" alt="statistics"/>
      <p>Below is an illustrative example of how carbon footprint offsetting occurs through our integration. Upon successful completion, the <g-link to="https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.rpc.ipci.io#/explorer/query/0xfc8cea3514805f8f170ab0a06e7787f86659197d607ddfde23e879efd105d737">transaction</g-link> unfolds as follows:</p>

      <div class="youtube-embed">
        <div class="youtube-embed__wrapper">
          <div class="youtube-embed__container">
              <iframe width="860" height="480" src="https://www.youtube.com/embed/bTbxCO9Yx68" title="Carbon Footprint Compensation Experiment in BBF's building" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture;" allowfullscreen></iframe>
          </div>
        </div>
      </div>

    </section>
  </CaseLayout>
</template>



<script>
export default {

  components: {
   CaseLayout: () => import('~/layouts/CaseLayout.vue'),
   CaseText: () => import('~/components/case/CaseText.vue'),
  }

}
</script>

<style>

  .case-page__content {
    margin-bottom: calc(var(--space) * 2);
  }
  

  .case-page__content h2 {
    margin-bottom: calc(var(--space) * 0.5);
    text-align: left;
    text-transform: unset;
    font-family: var(--font-family);
    font-size: calc(var(--base-font-size) * 1.3);
    font-weight: 800;
    letter-spacing: 0;
  }

</style>