<template>
  <layout>

    <MetaInfo
      pageTitle = "Privacy Policy"
      pageDescription = "This Policy describes the information we collect from you, how we use that information and our legal basis for doing so. It also covers whether and how that information may be shared and your rights and choices regarding the information you provide to us."
    />

    <article class="privacy-policy">
      <div class="layout layout__content">
        <h1 class="text-center">{{$t('Privacy Policy')}}</h1>
        <span class="privacy-policy__updated block mb-space text-center highlight-green"><em>{{ $t('Last updated: February 03, 2025') }}</em></span>

          <p class="privacy-policy__descr">{{$t('This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.')}}</p>

          <p class="privacy-policy__descr">{{$t('We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.')}}</p>


          <div class="privacy-policy__wrapper">
            <h2 class="privacy-policy__subtitle title-lined">
              <span>{{$t('Interpretation and Definitions')}}</span>
            </h2>
            <h3>{{ $t('Interpretation') }}</h3>
            <p class="privacy-policy__descr">{{$t("The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.")}}</p>

            <h3>{{$t('Definitions')}}</h3>
            <p class="privacy-policy__descr">{{ $t('For the purposes of this Privacy Policy:') }}</p>
            <ul>
              <li>
                <strong>{{$t('DAO')}}</strong> {{ $t('(referred to as either "the DAO", "We", "Us" or "Our" in this Agreement) refers to decentralized autonomous organization Robonomics Network, an operator for website')}} <g-link to="/">robonomics.network </g-link> {{$t('(referred to as') }} <strong>{{ $t('Website') }}</strong> {{ $t('in this Agreement). For the purpose of the GDPR, the DAO is the Data Controller.')}}
              </li>
              <li><strong>{{$t('Cookies')}}</strong> {{ $t('are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. More detailed information on cookies and how they work can be found at:') }} <g-link to="https://allaboutcookies.org/">https://allaboutcookies.org/</g-link></li>
              <li><strong>{{$t('Country')}}</strong> {{ $t('refers to: Cyprus.') }}</li>
              <li><strong>{{ $t('Data Controller') }}</strong>, {{ $t('for the purposes of the GDPR (General Data Protection Regulation), refers to the DAO as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.') }}</li>
              <li><strong>{{ $t('Device') }}</strong> {{ $t('means any device that can access the Service such as a computer, a cellphone or a digital tablet.') }}</li>
              <li><strong>{{ $t('GDPR') }}</strong> {{ $t('refers to EU General Data Protection Regulation.') }}</li>
              <li>
                <strong>{{ $t('Personal Data') }}</strong> {{ $t('is any information that relates to an identified or identifiable individual.') }}
                <p class="privacy-policy__descr">{{$t('For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity.')}}</p>
              </li>
              <li><strong>{{ $t('Service') }}</strong> {{ $t('refers to the Website') }}.</li>
              <li><strong>{{ $t('Service Provider') }}</strong> {{ $t('means any natural or legal person who processes the data on behalf of the DAO. It refers to third-party companies or individuals employed by the DAO to facilitate the Service, to provide the Service on behalf of the DAO, to perform services related to the Service or to assist the DAO in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.') }}</li>
              <li><strong>{{$t('Usage Data')}}</strong> {{ $t('refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).') }}</li>
              <li>
                <strong>{{ $t('You') }}</strong> {{ $t('(referred to as either "Your" in this Agreement) means the individual accessing or using the Service, or the DAO, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.') }}
                <p class="privacy-policy__descr">{{ $t('Under GDPR, You can be referred to as the Data Subject or as the User as you are the individual using the Service.') }}</p>
              </li>
            </ul>

          </div>

          <div class="privacy-policy__wrapper">
            <h2 class="privacy-policy__subtitle title-lined">
              <span>{{$t('Collecting and Using Your Personal Data')}}</span>
            </h2>
            <h3>{{ $t('Types of Data Collected') }}</h3>
            <h4>{{$t('Personal Data')}}</h4>
            <p class="privacy-policy__descr">{{$t('While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:')}}:</p>

            <ul>
              <li>{{ $t('Email address') }}</li>
              <li>{{ $t('First name and last name') }}</li>
              <li>{{$t('Usage Data')}}</li>
            </ul>

            <h4>{{ $t('Usage Data') }}</h4>
            <p class="privacy-policy__descr">{{ $t('Usage Data is collected automatically when using the Service.') }}</p>
            <p class="privacy-policy__descr">{{ $t("Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.") }}</p>
            <p class="privacy-policy__descr">{{ $t('When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.') }}</p>
            <p class="privacy-policy__descr">{{ $t('We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.') }}</p>

            <h4>{{ $t('Cookies & Browser Storage') }}</h4>
            <p class="policy-privacy__descr">{{ $t('The Websites may use cookies. We use cookies and browser storage only for essential settings to improve your experience—not for tracking. These help remember your preferences, such as language settings or consent choices, so you don’t have to reset them each time you visit.') }}</p>
            <p>{{ $t('We do not use cookies for tracking or personalized advertising. You can manage or disable cookies in your browser settings, but some features may not work properly without them.') }}</p>

            <h3 class="privacy-policy__subtitle">{{ $t('Matomo Analytics') }}</h3>
            <p class="privacy-policy__descr">{{$t('Our website may use Matomo, an open-source analytics platform, to gather insights into website usage. This includes anonymized data such as:')}}</p>

            <ul>
              <li>{{ $t('Pages visited and navigation paths') }}</li>
              <li>{{ $t('Time spent on our website') }}</li>
              <li>{{ $t('Whether you’re a returning or new visitor') }}</li>
              <li>{{ $t('Your device type (desktop, mobile, etc.)') }}</li>
            </ul>

            <p class="privacy-policy__descr">{{ $t('To protect your privacy, your IP address is anonymized before being stored. The data we collect is only used to improve the website and is not used for personal identification.') }}</p>

            <p class="policy-privacy__descr">
              <strong>{{ $t('Under Art. 6(1)(f) GDPR') }}</strong>, {{ $t('we process this data based on our legitimate interest in enhancing our services.') }}
            </p>

            <h4>{{ $t('Opt-Out Option') }}</h4>
            <p>{{$t('You can disable Matomo tracking at any time:') }}</p>

            <MatomoOptOutForm/>

            <h3 class="privacy-policy__subtitle">{{ $t('Use of Your Personal Data') }}</h3>
            <p class="privacy-policy__descr">
              {{ $t('The DAO may use Personal Data for the following purposes:') }}
            </p>
            <ul>
              <li><strong>{{$t('To provide and maintain our Service')}}</strong>, {{ $t('including to monitor the usage of our Service.') }}</li>
              <li><strong>{{$t('For the performance of a contract')}}</strong>: {{ $t('the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.') }}</li>
              <li><strong>{{$t('To contact You')}}</strong>: {{ $t("To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.") }}</li>
              <li><strong>{{$t('To provide You')}}</strong> {{ $t("with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.") }}</li>
              <li><strong>{{$t('To manage Your requests')}}</strong>: {{ $t("To attend and manage Your requests to Us.") }}</li>
              <li><strong>{{$t('For other purposes')}}</strong>: {{ $t("We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.") }}</li>
            </ul>
            <p class="policy-privacy__descr">
              {{ $t('We may share Your personal information in the following situations:') }}
            </p>
            <ul>
              <li><strong>{{ $t('With Service Providers') }}</strong>: {{ $t('We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.') }}</li>
              <li><strong>{{ $t('With Your consent') }}</strong>: {{ $t('We may disclose Your personal information for any other purpose with Your consent.') }}</li>
            </ul>

          <h3 class="privacy-policy__subtitle">{{ $t('Retention of Your Personal Data') }}</h3>
          <p class="privacy-policy__descr">
            {{ $t('The DAO will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.') }}
          </p>
          <p class="privacy-policy__descr">{{ $t('The DAO will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.') }}</p>

          <h3>{{ $t('Security of Your Personal Data') }}</h3>
          <p class="privacy-policy__descr">{{ $t('The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.') }}</p>
        </div>


        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t('Detailed Information on the Processing of Your Personal Data')}}</span>
          </h2>
          <p class="privacy-policy__descr">
            {{ $t("Your information, including Personal Data, is processed is processed at the DAO's website service provider(s) and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.") }}
          </p>
          <p class="privacy-policy__descr">{{ $t('Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.') }}
          </p>
          <p class="privacy-policy__descr">{{ $t('The DAO will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.') }}</p>
          <p class="privacy-policy__descr">{{ $t('Please note that any data transmission on the Internet (e.g. communication by e-mail) is generally not secure and we accept no liability for data transmitted to us via the Internet. Unfortunately, absolute protection is not technically possible. This information does not apply to the Website of third parties and the corresponding links given on our Website. The DAO assumes no responsibility and liability for these.') }}</p>

          <p class="privacy-policy__descr">{{$t("The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.")}}</p>

          <h3>{{$t('Email Marketing')}}</h3>
          <p class="privacy-policy__descr">{{ $t('We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.') }}</p>
          <p class="privacy-policy__descr">{{ $t('We may use Email Marketing Service Providers to manage and send emails to You;') }}</p>
          <ul>
            <li>
              <strong>{{ $t('Unisender') }}</strong> 
              <p class="privacy-policy__descr">{{ $t('Their Privacy Policy can be viewed at') }} <g-link to="https://www.unisender.com/ru/privacy-notice">https://www.unisender.com/ru/privacy-notice/</g-link></p>
            </li>
          </ul>

          <h3>{{ $t('Usage, Performance and Miscellaneous') }}</h3>
          <p class="privacy-policy__descr">{{ $t('We may use third-party Service Providers to maintain and improve our Service.') }}</p>
          <ul>
            <li>
              <strong>{{ $t('hcaptcha') }}</strong> 
              <p class="privacy-policy__descr">{{ $t('Their Privacy Policy can be viewed at') }} <g-link to="https://www.hcaptcha.com/privacy"> https://www.hcaptcha.com/privacy</g-link></p>
            </li>
          </ul>
        </div>

        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t('GDPR Privacy')}}</span>
          </h2>
          <h3>{{ $t('Legal Basis for Processing Personal Data under GDPR') }}</h3>
          <p class="privacy-policy__descr">{{$t("We may process Personal Data under the following conditions:")}}</p>
          <ul>
            <li>
              <strong>{{ $t('Consent:') }}</strong> {{ $t('You have given Your consent for processing Personal Data for one or more specific purposes.') }}
            </li>
            <li>
              <strong>{{ $t('Performance of a contract:') }}</strong> {{ $t('Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.') }}
            </li>
            <li>
              <strong>{{ $t('Legal obligations:') }}</strong> {{ $t('Processing Personal Data is necessary for compliance with a legal obligation to which the DAO is subject.') }}
            </li>
            <li>
              <strong>{{ $t('Vital interests:') }}</strong> {{ $t('Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.') }}
            </li>
            <li>
              <strong>{{ $t('Public interests:') }}</strong> {{ $t('Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the DAO.') }}
            </li>
            <li>
              <strong>{{ $t('Legitimate interests:') }}</strong> {{ $t('Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the DAO.') }}
            </li>
          </ul>
          <p class="privacy-policy__descr">{{ $t('In any case, the DAO will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.') }}</p>

          <h3>{{ $t('Your Rights under the GDPR') }}</h3>
          <p class="privacy-policy__descr">{{ $t('The DAO undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.') }}</p>
          <p class="privacy-policy__descr">{{ $t('You have the right under this Privacy Policy, and by law if You are within the EU, to:') }}</p>
          <ul>
            <li><strong>{{ $t('Request access to Your Personal Data.') }}</strong> {{ $t('The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.') }}</li>
            <li><strong>{{ $t('Request correction of the Personal Data that We hold about You.') }}</strong> {{ $t('You have the right to have any incomplete or inaccurate information We hold about You corrected.') }}</li>
            <li><strong>{{ $t('Object to processing of Your Personal Data.') }}</strong> {{ $t('This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.') }}</li>
            <li><strong>{{ $t('Request erasure of Your Personal Data.') }}</strong> {{ $t('You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.') }}</li>
            <li><strong>{{ $t('Request the transfer of Your Personal Data.') }}</strong> {{ $t('We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.') }}</li>
            <li><strong>{{ $t('Withdraw Your consent.') }}</strong> {{ $t('You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.') }}</li>
          </ul>

          <h3>{{ $t('Exercising of Your GDPR Data Protection Rights') }}</h3>
          <p class="privacy-policy__descr">{{ $t('You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.') }}</p>
          <p class="privacy-policy__descr">{{ $t('You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.') }}</p>
        </div>

        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t("Children's Privacy")}}</span>
          </h2>
          <p class="privacy-policy__descr">{{$t("Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.")}}</p>
          <p class="privacy-policy__descr">{{$t("If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.")}}</p>
        </div>
        

        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t("Links to Other Websites")}}</span>
          </h2>
          <p class="privacy-policy__descr">{{$t("Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.")}}</p>
          <p class="privacy-policy__descr">{{$t("We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.")}}</p>
        </div>

        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t("Changes to this Privacy Policy")}}</span>
          </h2>
          <p class="privacy-policy__descr">{{$t("We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.")}}</p>
          <p class="privacy-policy__descr">{{$t('We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.')}}</p>
          <p class="privacy-policy__descr">{{$t('You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.')}}</p>
        </div>

        <div class="privacy-policy__wrapper">
          <h2 class="privacy-policy__subtitle title-lined">
            <span>{{$t("Contact Us")}}</span>
          </h2>
          <p class="privacy-policy__descr">{{$t("If you have any questions about this Privacy Policy, You can contact us:")}}</p>
          <ul>
            <li>{{ $t('By visiting this page on our website:') }} <g-link to="/contact">https://robonomics.network/contact/</g-link></li>
          </ul>
        </div>
      </div>

      <div class="layout layout__content text-small policy-privacy__ai">
        <p>{{ $t('This Agreement is originally written in English. This AI translation is provided for your reference only.') }}</p>
      </div>
    </article>
  </layout>
</template>

<script>
export default {

  components: {
    MetaInfo: () => import('~/components/MetaInfo.vue'),
    MatomoOptOutForm: () => import('~/components/MatomoOptOutForm.vue')
  }

}
</script>

<style scoped>

  ul {
    padding-left: calc(var(--space) * 0.5);
  }

  .privacy-policy.container__narrow {
    max-width: 850px;
  }

  .privacy-policy__wrapper:not(:first-child) {
    margin-top: calc(var(--space) * 3.5);
  }

  .privacy-policy__wrapper:not(:last-child) {
    margin-bottom: calc(var(--space) * 3.5);
  }

  .privacy-policy__subtitle {
    margin-bottom: calc(var(--space) * 0.5);
  }

  .policy-privacy__ai {
    margin-top: calc(var(--space) * 5);
    text-align: right;
  }

  @media screen and (max-width: 540px) {
    h1 {
      font-size: 1.6rem;
    }

    h2 {
      font-size: 1.4rem;
    }

    h3 {
      margin: var(--space) 0;
      font-size: 1.2rem;
    }
  }

</style>