name: Robonomics Network

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'  

      - name: Install packages
        run: yarn install 

      - name: Run yarn build
        run: yarn build  
        env: 
          PUBLIC_RECAPTCHA: ${{ secrets.PUBLIC_RECAPTCHA }}
          PUBLIC_CONTACTS_FORM_SCRIPT: ${{ secrets.PUBLIC_CONTACTS_FORM_SCRIPT }}
          PUBLIC_RENT_KEY: ${{ secrets.PUBLIC_RENT_KEY }}

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: robonomics.network
