# This is a basic workflow to help you get started with Actions

name: Robonomics Network

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install and Build 🔧
        run: |
          sudo npm install --global @gridsome/cli
          npm ci
          export NODE_OPTIONS="--max_old_space_size=4096"
          gridsome build
        env:
          FORM_SCRIPT: ${{ secrets.FORM_SCRIPT }}
          GRIDSOME_RECAPTCHA: ${{ secrets.GRIDSOME_RECAPTCHA }}
          GRIDSOME_CONTACTS_FORM_SCRIPT: ${{ secrets.GRIDSOME_CONTACTS_FORM_SCRIPT }}
          GRIDSOME_UNISENDER_LIST_ID: ${{ secrets.GRIDSOME_UNISENDER_LIST_ID }}
          GRIDSOME_UNISENDER_KEY: ${{ secrets.GRIDSOME_UNISENDER_KEY }}
          GRIDSOME_TG_CHAT_ID: ${{ secrets.GRIDSOME_TG_CHAT_ID }}
          GRIDSOME_TG_TOKEN: ${{ secrets.GRIDSOME_TG_TOKEN }}

      - name: Deploy
        #uses: JamesIves/github-pages-deploy-action@3.7.1
        #with:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  BRANCH: gh-pages # The branch the action should deploy to.
        #  FOLDER: dist # The folder the action should deploy.
        #  CLEAN: true # Automatically remove deleted files from the deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: robonomics.network
